# Option 1: Use git-gateway with Netlify Identity (recommended for Netlify)
backend:
  name: git-gateway
  branch: main

# Option 2: Use GitHub backend for Vercel (uncomment below and comment above)
# backend:
#   name: github
#   repo: OxfordUniRacing/OUR_website
#   branch: main
#   base_url: https://api.netlify.com
#   auth_endpoint: auth

# Option 3: Use test-repo backend for local testing (uncomment for development)
# backend:
#   name: test-repo

# For local development only (uncomment when testing locally)
# local_backend: true

# Media storage configuration
media_folder: public/images
public_folder: /images

# For Cloudinary (uncomment when ready):
# media_library:
#   name: cloudinary
#   config:
#     cloud_name: your_cloud_name_here
#     api_key: your_api_key_here

collections:
  - name: "news"
    label: "News Articles"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Featured Image", name: "featuredImage", widget: "image", required: false }
      - { label: "Excerpt", name: "excerpt", widget: "text", hint: "Brief summary (max 200 characters)" }
      - { label: "Tags", name: "tags", widget: "list", default: [] }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "team"
    label: "Team Members"
    folder: "content/team"
    create: true
    slug: "{{subteam}}/{{name}}"
    path: "{{subteam}}/{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string", hint: "Full name of team member" }
      - { label: "Role", name: "role", widget: "string", hint: "Position or title (e.g., Team Principal, Lead Engineer)" }
      - { label: "Sub-team", name: "subteam", widget: "select", options: ["leadership", "aerodynamics", "chassis", "powertrain", "electronics", "operations"], hint: "Which sub-team the member belongs to" }
      - { label: "Profile Image", name: "image", widget: "image", required: false, hint: "Professional headshot (square format recommended)" }
      - { label: "Email", name: "email", widget: "string", required: false, hint: "Contact email (optional)" }
      - { label: "LinkedIn", name: "linkedin", widget: "string", required: false, hint: "LinkedIn profile URL (optional)" }
      - { label: "Year of Study", name: "year", widget: "number", value_type: "int", min: 1, max: 5, hint: "Current year of study" }
      - { label: "Course", name: "course", widget: "string", hint: "Degree program" }
      - { label: "Bio", name: "body", widget: "markdown", hint: "Brief background, interests, and role description" }

  - name: "sponsors"
    label: "Partners"
    folder: "content/sponsors"
    create: true
    slug: "{{fields.name}}"
    fields:
      - { label: "Name", name: "name", widget: "string", hint: "Organization or company name" }
      - { label: "Logo", name: "logo", widget: "image", hint: "Upload company logo (PNG/JPG, high resolution recommended)" }
      - { label: "Website", name: "website", widget: "string", required: false, hint: "Company website URL (optional)" }
      - { label: "Partner Since", name: "since", widget: "number", value_type: "int", required: false, hint: "Year partnership began (optional)" }
      - { label: "Description", name: "body", widget: "markdown", hint: "Brief description of the organization and partnership" }

  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{fields.title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }

# Site settings (will be updated after Netlify deployment)
site_url: https://subtle-sawine-4de7d5.netlify.app # Update this with your actual Netlify URL